/**
 * Proactive Companion Engine — shared type definitions.
 *
 * Defines the trigger system, message format, cooldown config,
 * and engine status types used across the companion subsystem.
 */

import type { Emotion } from '../../buddy/sprite-atlas.js'

// ── Trigger Types ─────────────────────────────────────────────────────────

/** The four categories of proactive interjections. */
export type TriggerType = 'time' | 'behavior' | 'market' | 'encouragement'

/** Severity determines cooldown bypass and message urgency. */
export type ProactiveSeverity = 'gentle' | 'firm' | 'urgent'

// ── Proactive Message ─────────────────────────────────────────────────────

/** A message generated by the proactive monitor, ready for delivery. */
export interface ProactiveMessage {
  /** Which trigger category produced this message. */
  trigger: TriggerType
  /** Urgency level — 'urgent' bypasses cooldown. */
  severity: ProactiveSeverity
  /** The master's message text (already styled per archetype). */
  message: string
  /** Emotion to set on the ExpressionEngine. */
  emotion: Emotion
}

// ── Trading Event ─────────────────────────────────────────────────────────

/** Events from the trading system that the companion engine can react to. */
export interface TradingEvent {
  type: 'trade_executed' | 'position_opened' | 'position_closed' | 'order_placed'
  symbol: string
  side: 'buy' | 'sell'
  quantity: number
  price: number
  pnlPercent?: number
}

// ── Configuration ─────────────────────────────────────────────────────────

/** Configuration for the CompanionEngine. */
export interface CompanionConfig {
  /** Master kill switch. */
  enabled: boolean
  /** Whether proactive interjections are active. */
  proactiveEnabled: boolean
  /** Minimum milliseconds between non-urgent messages. Default: 300_000 (5 min). */
  cooldownMs: number
  /** Epoch timestamp when the current session started. */
  sessionStartTime: number
}

// ── Engine Status ─────────────────────────────────────────────────────────

/** Runtime status snapshot of the CompanionEngine. */
export interface CompanionStatus {
  /** Whether the engine is currently running. */
  running: boolean
  /** Whether proactive monitoring is active. */
  proactiveActive: boolean
  /** Total proactive messages delivered this session. */
  messagesDelivered: number
  /** Epoch timestamp of last delivered message, or null if none. */
  lastMessageAt: number | null
  /** Session duration in milliseconds. */
  sessionDurationMs: number
  /** Whether cooldown is currently active (non-urgent messages blocked). */
  cooldownActive: boolean
}
